name: 'Find and Lint API Changes'
description: 'Find files that have changed and match API definitions in .postman directory, optionally lint them with Postman CLI'
author: 'GitHub Copilot'

inputs:
  postman-directory:
    description: 'Directory containing Postman API files'
    required: false
    default: '.postman'
  base-ref:
    description: 'Base reference for comparison'
    required: false
    default: 'HEAD~1'
  run-lint:
    description: 'Whether to run API linting after detecting changes'
    required: false
    default: 'true'

outputs:
  api-changes:
    description: 'JSON array of changed API files'
    value: ${{ steps.find-changes.outputs.api-changes }}
  has-changes:
    description: 'Whether any API changes were found'
    value: ${{ steps.find-changes.outputs.has-changes }}
  lint-results:
    description: 'Results of API linting (if run-lint is enabled)'
    value: ${{ steps.find-changes.outputs.lint-results }}

runs:
  using: 'node20'
  main: 'dist/index.js'
