name: Find and lint modified APIs

on:
  workflow_dispatch:
  push:
    paths:
      - '**.yaml'
      - '**.yml'

 


jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.api-changes.outputs.has-changes }}
      api-changes: ${{ steps.api-changes.outputs.api-changes }}
      matrix-data: ${{ steps.prepare-matrix.outputs.matrix-data }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    # Using the action with all defaults
    - name: Find API changes
      id: api-changes
      uses: ./
    
    - name: Show results
      run: |
        if [ "${{ steps.api-changes.outputs.has-changes }}" == "true" ]; then
          echo "API changes detected!"
          echo '${{ steps.api-changes.outputs.api-changes }}' | jq '.'
        else
          echo "No API changes detected"
        fi
    
    - name: Prepare matrix data
      id: prepare-matrix
      if: steps.api-changes.outputs.has-changes == 'true'
      run: |
        matrix_data=$(echo '${{ steps.api-changes.outputs.api-changes }}' | jq -c '{include: [.[] | {apiId: .apiId, rootFile: .rootFile, integrationId: .integrationId}]}')
        echo "matrix-data=$matrix_data" >> $GITHUB_OUTPUT
        echo "Matrix data: $matrix_data"

  lint-apis:
    needs: detect-changes
    if: needs.detect-changes.outputs.has-changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix-data) }}
      fail-fast: false
    
    name: Lint API ${{ matrix.rootFile }} - ${{ matrix.apiId }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Postman CLI
      run: |
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
        echo "$HOME/.postman/bin" >> $GITHUB_PATH
        postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
    
    - name: Lint API
      run: |
        echo "Linting API: ${{ matrix.apiId }}"
        echo "Root file: ${{ matrix.rootFile }}"
        echo "Integration ID: ${{ matrix.integrationId }}"
        
        if [ "${{ matrix.integrationId }}" != "null" ] && [ -n "${{ matrix.integrationId }}" ]; then
          echo "Running: postman api lint ${{ matrix.apiId }} --integration-id ${{ matrix.integrationId }}"
          postman api lint "${{ matrix.apiId }}" --integration-id "${{ matrix.integrationId }}"
          
        else
          echo "Running: postman api lint ${{ matrix.apiId }}"
          postman api lint "${{ matrix.apiId }}"
        fi
