name: Test Find API Changes

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-action:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for better diff comparison
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Test as reusable action
      id: api-changes
      uses: ./
      with:
        postman-directory: '.postman'
        base-ref: 'HEAD~1'
        output-format: 'github'
    
    - name: Display results
      run: |
        echo "### API Changes Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Has Changes:** ${{ steps.api-changes.outputs.has-changes }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Details:**" >> $GITHUB_STEP_SUMMARY
        echo '```json' >> $GITHUB_STEP_SUMMARY
        echo '${{ steps.api-changes.outputs.api-changes }}' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
    
    - name: Test standalone script
      run: |
        echo "Testing standalone script..."
        node .github/scripts/find-api-changes.js
